/* tslint:disable */
/* eslint-disable */
/**
 * Project/App Name APIs — v1
 * API v1 documentation for the backend services of Project/App Name
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UpdateUserDto,
} from '../models/index';

export interface UsersControllerFindAllV1Request {
    page?: number;
    pageSize?: number;
}

export interface UsersControllerFindByIdV1Request {
    id: string;
}

export interface UsersControllerRemoveV1Request {
    id: string;
}

export interface UsersControllerUpdateMyProfileV1Request {
    updateUserDto: UpdateUserDto;
}

/**
 * UsersApi - interface
 * 
 * @export
 * @interface UsersApiInterface
 */
export interface UsersApiInterface {
    /**
     * 
     * @summary List all users with pagination
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    usersControllerFindAllV1Raw(requestParameters: UsersControllerFindAllV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * List all users with pagination
     */
    usersControllerFindAllV1(requestParameters: UsersControllerFindAllV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get user by ID
     * @param {string} id User UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    usersControllerFindByIdV1Raw(requestParameters: UsersControllerFindByIdV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Get user by ID
     */
    usersControllerFindByIdV1(requestParameters: UsersControllerFindByIdV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get current user profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    usersControllerGetMyProfileV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Get current user profile
     */
    usersControllerGetMyProfileV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Soft delete a user
     * @param {string} id User UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    usersControllerRemoveV1Raw(requestParameters: UsersControllerRemoveV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Soft delete a user
     */
    usersControllerRemoveV1(requestParameters: UsersControllerRemoveV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Update current user profile
     * @param {UpdateUserDto} updateUserDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    usersControllerUpdateMyProfileV1Raw(requestParameters: UsersControllerUpdateMyProfileV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Update current user profile
     */
    usersControllerUpdateMyProfileV1(requestParameters: UsersControllerUpdateMyProfileV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI implements UsersApiInterface {

    /**
     * List all users with pagination
     */
    async usersControllerFindAllV1Raw(requestParameters: UsersControllerFindAllV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/users`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * List all users with pagination
     */
    async usersControllerFindAllV1(requestParameters: UsersControllerFindAllV1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersControllerFindAllV1Raw(requestParameters, initOverrides);
    }

    /**
     * Get user by ID
     */
    async usersControllerFindByIdV1Raw(requestParameters: UsersControllerFindByIdV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling usersControllerFindByIdV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/users/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get user by ID
     */
    async usersControllerFindByIdV1(requestParameters: UsersControllerFindByIdV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersControllerFindByIdV1Raw(requestParameters, initOverrides);
    }

    /**
     * Get current user profile
     */
    async usersControllerGetMyProfileV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/users/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get current user profile
     */
    async usersControllerGetMyProfileV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersControllerGetMyProfileV1Raw(initOverrides);
    }

    /**
     * Soft delete a user
     */
    async usersControllerRemoveV1Raw(requestParameters: UsersControllerRemoveV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling usersControllerRemoveV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/users/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft delete a user
     */
    async usersControllerRemoveV1(requestParameters: UsersControllerRemoveV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersControllerRemoveV1Raw(requestParameters, initOverrides);
    }

    /**
     * Update current user profile
     */
    async usersControllerUpdateMyProfileV1Raw(requestParameters: UsersControllerUpdateMyProfileV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['updateUserDto'] == null) {
            throw new runtime.RequiredError(
                'updateUserDto',
                'Required parameter "updateUserDto" was null or undefined when calling usersControllerUpdateMyProfileV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/users/me`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['updateUserDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update current user profile
     */
    async usersControllerUpdateMyProfileV1(requestParameters: UsersControllerUpdateMyProfileV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersControllerUpdateMyProfileV1Raw(requestParameters, initOverrides);
    }

}
