global:
  scrape_interval: 30s
  scrape_timeout: 15s
  evaluation_interval: 30s

rule_files:
  - '/etc/prometheus/rules.yml'
  - '/etc/prometheus/alerts.yml'
  - '/etc/prometheus/healops-alerts.yml'

scrape_configs:
  - job_name: 'nestjs_app'
    metrics_path: '/metrics'
    scheme: http
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - 'host.docker.internal:4000'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*):.*'
        replacement: '${1}'
        action: replace
