/* tslint:disable */
/* eslint-disable */
/**
 * Project/App Name APIs — v1
 * API v1 documentation for the backend services of Project/App Name
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChatRequestDto,
} from '../models/index';

export interface AgentsControllerChatV1Request {
    chatRequestDto: ChatRequestDto;
}

export interface AgentsControllerDeleteConversationV1Request {
    id: string;
}

export interface AgentsControllerGetConversationV1Request {
    id: string;
}

export interface AgentsControllerListConversationsV1Request {
    page?: number;
    pageSize?: number;
}

/**
 * AIApi - interface
 * 
 * @export
 * @interface AIApiInterface
 */
export interface AIApiInterface {
    /**
     * Sends a message and receives a response. If conversationId is provided, the message is appended to an existing conversation. Otherwise, a new conversation is created. The agent may use tools (RAG search, database, etc.) to gather information before responding.
     * @summary Send a message to the AI agent
     * @param {ChatRequestDto} chatRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AIApiInterface
     */
    agentsControllerChatV1Raw(requestParameters: AgentsControllerChatV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Sends a message and receives a response. If conversationId is provided, the message is appended to an existing conversation. Otherwise, a new conversation is created. The agent may use tools (RAG search, database, etc.) to gather information before responding.
     * Send a message to the AI agent
     */
    agentsControllerChatV1(requestParameters: AgentsControllerChatV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Permanently deletes a conversation and all its messages.
     * @summary Delete a conversation
     * @param {string} id Conversation UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AIApiInterface
     */
    agentsControllerDeleteConversationV1Raw(requestParameters: AgentsControllerDeleteConversationV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Permanently deletes a conversation and all its messages.
     * Delete a conversation
     */
    agentsControllerDeleteConversationV1(requestParameters: AgentsControllerDeleteConversationV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Returns a single conversation including all its messages.
     * @summary Get a conversation with messages
     * @param {string} id Conversation UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AIApiInterface
     */
    agentsControllerGetConversationV1Raw(requestParameters: AgentsControllerGetConversationV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Returns a single conversation including all its messages.
     * Get a conversation with messages
     */
    agentsControllerGetConversationV1(requestParameters: AgentsControllerGetConversationV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Returns a paginated list of the authenticated user\'s conversations.
     * @summary List user conversations
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AIApiInterface
     */
    agentsControllerListConversationsV1Raw(requestParameters: AgentsControllerListConversationsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Returns a paginated list of the authenticated user\'s conversations.
     * List user conversations
     */
    agentsControllerListConversationsV1(requestParameters: AgentsControllerListConversationsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class AIApi extends runtime.BaseAPI implements AIApiInterface {

    /**
     * Sends a message and receives a response. If conversationId is provided, the message is appended to an existing conversation. Otherwise, a new conversation is created. The agent may use tools (RAG search, database, etc.) to gather information before responding.
     * Send a message to the AI agent
     */
    async agentsControllerChatV1Raw(requestParameters: AgentsControllerChatV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['chatRequestDto'] == null) {
            throw new runtime.RequiredError(
                'chatRequestDto',
                'Required parameter "chatRequestDto" was null or undefined when calling agentsControllerChatV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ai/chat`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['chatRequestDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Sends a message and receives a response. If conversationId is provided, the message is appended to an existing conversation. Otherwise, a new conversation is created. The agent may use tools (RAG search, database, etc.) to gather information before responding.
     * Send a message to the AI agent
     */
    async agentsControllerChatV1(requestParameters: AgentsControllerChatV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.agentsControllerChatV1Raw(requestParameters, initOverrides);
    }

    /**
     * Permanently deletes a conversation and all its messages.
     * Delete a conversation
     */
    async agentsControllerDeleteConversationV1Raw(requestParameters: AgentsControllerDeleteConversationV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling agentsControllerDeleteConversationV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ai/conversations/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently deletes a conversation and all its messages.
     * Delete a conversation
     */
    async agentsControllerDeleteConversationV1(requestParameters: AgentsControllerDeleteConversationV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.agentsControllerDeleteConversationV1Raw(requestParameters, initOverrides);
    }

    /**
     * Returns a single conversation including all its messages.
     * Get a conversation with messages
     */
    async agentsControllerGetConversationV1Raw(requestParameters: AgentsControllerGetConversationV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling agentsControllerGetConversationV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ai/conversations/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Returns a single conversation including all its messages.
     * Get a conversation with messages
     */
    async agentsControllerGetConversationV1(requestParameters: AgentsControllerGetConversationV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.agentsControllerGetConversationV1Raw(requestParameters, initOverrides);
    }

    /**
     * Returns a paginated list of the authenticated user\'s conversations.
     * List user conversations
     */
    async agentsControllerListConversationsV1Raw(requestParameters: AgentsControllerListConversationsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ai/conversations`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Returns a paginated list of the authenticated user\'s conversations.
     * List user conversations
     */
    async agentsControllerListConversationsV1(requestParameters: AgentsControllerListConversationsV1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.agentsControllerListConversationsV1Raw(requestParameters, initOverrides);
    }

}
