/* tslint:disable */
/* eslint-disable */
/**
 * Project/App Name APIs — v1
 * API v1 documentation for the backend services of Project/App Name
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChangePasswordDto,
  LoginDto,
  MfaVerifyDto,
  RefreshTokenDto,
  RegisterDto,
} from '../models/index';

export interface AuthControllerChangePasswordV1Request {
    changePasswordDto: ChangePasswordDto;
}

export interface AuthControllerLoginV1Request {
    loginDto: LoginDto;
}

export interface AuthControllerMfaVerifyV1Request {
    mfaVerifyDto: MfaVerifyDto;
}

export interface AuthControllerRefreshV1Request {
    refreshTokenDto: RefreshTokenDto;
}

export interface AuthControllerRegisterV1Request {
    registerDto: RegisterDto;
}

/**
 * AuthApi - interface
 * 
 * @export
 * @interface AuthApiInterface
 */
export interface AuthApiInterface {
    /**
     * 
     * @summary Change the current user password
     * @param {ChangePasswordDto} changePasswordDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    authControllerChangePasswordV1Raw(requestParameters: AuthControllerChangePasswordV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Change the current user password
     */
    authControllerChangePasswordV1(requestParameters: AuthControllerChangePasswordV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary GitHub OAuth callback
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    authControllerGithubAuthCallbackV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * GitHub OAuth callback
     */
    authControllerGithubAuthCallbackV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Initiate GitHub OAuth login
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    authControllerGithubAuthV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Initiate GitHub OAuth login
     */
    authControllerGithubAuthV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Google OAuth callback
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    authControllerGoogleAuthCallbackV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Google OAuth callback
     */
    authControllerGoogleAuthCallbackV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Initiate Google OAuth login
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    authControllerGoogleAuthV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Initiate Google OAuth login
     */
    authControllerGoogleAuthV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Authenticate with email and password
     * @param {LoginDto} loginDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    authControllerLoginV1Raw(requestParameters: AuthControllerLoginV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Authenticate with email and password
     */
    authControllerLoginV1(requestParameters: AuthControllerLoginV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Logout and revoke all refresh tokens
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    authControllerLogoutV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Logout and revoke all refresh tokens
     */
    authControllerLogoutV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Set up TOTP-based multi-factor authentication
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    authControllerMfaSetupV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Set up TOTP-based multi-factor authentication
     */
    authControllerMfaSetupV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Verify a TOTP code to complete MFA setup or authenticate
     * @param {MfaVerifyDto} mfaVerifyDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    authControllerMfaVerifyV1Raw(requestParameters: AuthControllerMfaVerifyV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Verify a TOTP code to complete MFA setup or authenticate
     */
    authControllerMfaVerifyV1(requestParameters: AuthControllerMfaVerifyV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Refresh access token using a refresh token
     * @param {RefreshTokenDto} refreshTokenDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    authControllerRefreshV1Raw(requestParameters: AuthControllerRefreshV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Refresh access token using a refresh token
     */
    authControllerRefreshV1(requestParameters: AuthControllerRefreshV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Register a new user account
     * @param {RegisterDto} registerDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    authControllerRegisterV1Raw(requestParameters: AuthControllerRegisterV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Register a new user account
     */
    authControllerRegisterV1(requestParameters: AuthControllerRegisterV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI implements AuthApiInterface {

    /**
     * Change the current user password
     */
    async authControllerChangePasswordV1Raw(requestParameters: AuthControllerChangePasswordV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['changePasswordDto'] == null) {
            throw new runtime.RequiredError(
                'changePasswordDto',
                'Required parameter "changePasswordDto" was null or undefined when calling authControllerChangePasswordV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/auth/change-password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['changePasswordDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Change the current user password
     */
    async authControllerChangePasswordV1(requestParameters: AuthControllerChangePasswordV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerChangePasswordV1Raw(requestParameters, initOverrides);
    }

    /**
     * GitHub OAuth callback
     */
    async authControllerGithubAuthCallbackV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/github/callback`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * GitHub OAuth callback
     */
    async authControllerGithubAuthCallbackV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerGithubAuthCallbackV1Raw(initOverrides);
    }

    /**
     * Initiate GitHub OAuth login
     */
    async authControllerGithubAuthV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/github`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Initiate GitHub OAuth login
     */
    async authControllerGithubAuthV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerGithubAuthV1Raw(initOverrides);
    }

    /**
     * Google OAuth callback
     */
    async authControllerGoogleAuthCallbackV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/google/callback`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Google OAuth callback
     */
    async authControllerGoogleAuthCallbackV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerGoogleAuthCallbackV1Raw(initOverrides);
    }

    /**
     * Initiate Google OAuth login
     */
    async authControllerGoogleAuthV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/google`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Initiate Google OAuth login
     */
    async authControllerGoogleAuthV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerGoogleAuthV1Raw(initOverrides);
    }

    /**
     * Authenticate with email and password
     */
    async authControllerLoginV1Raw(requestParameters: AuthControllerLoginV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['loginDto'] == null) {
            throw new runtime.RequiredError(
                'loginDto',
                'Required parameter "loginDto" was null or undefined when calling authControllerLoginV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['loginDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Authenticate with email and password
     */
    async authControllerLoginV1(requestParameters: AuthControllerLoginV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerLoginV1Raw(requestParameters, initOverrides);
    }

    /**
     * Logout and revoke all refresh tokens
     */
    async authControllerLogoutV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/auth/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Logout and revoke all refresh tokens
     */
    async authControllerLogoutV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerLogoutV1Raw(initOverrides);
    }

    /**
     * Set up TOTP-based multi-factor authentication
     */
    async authControllerMfaSetupV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/auth/mfa/setup`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Set up TOTP-based multi-factor authentication
     */
    async authControllerMfaSetupV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerMfaSetupV1Raw(initOverrides);
    }

    /**
     * Verify a TOTP code to complete MFA setup or authenticate
     */
    async authControllerMfaVerifyV1Raw(requestParameters: AuthControllerMfaVerifyV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['mfaVerifyDto'] == null) {
            throw new runtime.RequiredError(
                'mfaVerifyDto',
                'Required parameter "mfaVerifyDto" was null or undefined when calling authControllerMfaVerifyV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/auth/mfa/verify`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['mfaVerifyDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Verify a TOTP code to complete MFA setup or authenticate
     */
    async authControllerMfaVerifyV1(requestParameters: AuthControllerMfaVerifyV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerMfaVerifyV1Raw(requestParameters, initOverrides);
    }

    /**
     * Refresh access token using a refresh token
     */
    async authControllerRefreshV1Raw(requestParameters: AuthControllerRefreshV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['refreshTokenDto'] == null) {
            throw new runtime.RequiredError(
                'refreshTokenDto',
                'Required parameter "refreshTokenDto" was null or undefined when calling authControllerRefreshV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/refresh`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['refreshTokenDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Refresh access token using a refresh token
     */
    async authControllerRefreshV1(requestParameters: AuthControllerRefreshV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerRefreshV1Raw(requestParameters, initOverrides);
    }

    /**
     * Register a new user account
     */
    async authControllerRegisterV1Raw(requestParameters: AuthControllerRegisterV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['registerDto'] == null) {
            throw new runtime.RequiredError(
                'registerDto',
                'Required parameter "registerDto" was null or undefined when calling authControllerRegisterV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/register`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['registerDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Register a new user account
     */
    async authControllerRegisterV1(requestParameters: AuthControllerRegisterV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerRegisterV1Raw(requestParameters, initOverrides);
    }

}
