/* tslint:disable */
/* eslint-disable */
/**
 * Project/App Name APIs — v1
 * API v1 documentation for the backend services of Project/App Name
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface MediaControllerGetByIdV1Request {
    id: string;
}

export interface MediaControllerGetSignedUrlV1Request {
    id: string;
}

export interface MediaControllerListV1Request {
    page?: number;
    pageSize?: number;
}

export interface MediaControllerRemoveV1Request {
    id: string;
}

export interface MediaControllerUploadV1Request {
    file: Blob;
    metadata?: object | null;
}

/**
 * MediaApi - interface
 * 
 * @export
 * @interface MediaApiInterface
 */
export interface MediaApiInterface {
    /**
     * 
     * @summary Get a media file by ID
     * @param {string} id Media UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaApiInterface
     */
    mediaControllerGetByIdV1Raw(requestParameters: MediaControllerGetByIdV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Get a media file by ID
     */
    mediaControllerGetByIdV1(requestParameters: MediaControllerGetByIdV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get a presigned URL for a media file (ownership verified)
     * @param {string} id Media UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaApiInterface
     */
    mediaControllerGetSignedUrlV1Raw(requestParameters: MediaControllerGetSignedUrlV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Get a presigned URL for a media file (ownership verified)
     */
    mediaControllerGetSignedUrlV1(requestParameters: MediaControllerGetSignedUrlV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary List current user media files with pagination
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaApiInterface
     */
    mediaControllerListV1Raw(requestParameters: MediaControllerListV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * List current user media files with pagination
     */
    mediaControllerListV1(requestParameters: MediaControllerListV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Delete a media file (ownership verified)
     * @param {string} id Media UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaApiInterface
     */
    mediaControllerRemoveV1Raw(requestParameters: MediaControllerRemoveV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete a media file (ownership verified)
     */
    mediaControllerRemoveV1(requestParameters: MediaControllerRemoveV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Upload a media file
     * @param {Blob} file The file to upload
     * @param {object} [metadata] Optional JSON metadata
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaApiInterface
     */
    mediaControllerUploadV1Raw(requestParameters: MediaControllerUploadV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Upload a media file
     */
    mediaControllerUploadV1(requestParameters: MediaControllerUploadV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class MediaApi extends runtime.BaseAPI implements MediaApiInterface {

    /**
     * Get a media file by ID
     */
    async mediaControllerGetByIdV1Raw(requestParameters: MediaControllerGetByIdV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling mediaControllerGetByIdV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/media/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get a media file by ID
     */
    async mediaControllerGetByIdV1(requestParameters: MediaControllerGetByIdV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.mediaControllerGetByIdV1Raw(requestParameters, initOverrides);
    }

    /**
     * Get a presigned URL for a media file (ownership verified)
     */
    async mediaControllerGetSignedUrlV1Raw(requestParameters: MediaControllerGetSignedUrlV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling mediaControllerGetSignedUrlV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/media/{id}/signed-url`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get a presigned URL for a media file (ownership verified)
     */
    async mediaControllerGetSignedUrlV1(requestParameters: MediaControllerGetSignedUrlV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.mediaControllerGetSignedUrlV1Raw(requestParameters, initOverrides);
    }

    /**
     * List current user media files with pagination
     */
    async mediaControllerListV1Raw(requestParameters: MediaControllerListV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/media`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * List current user media files with pagination
     */
    async mediaControllerListV1(requestParameters: MediaControllerListV1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.mediaControllerListV1Raw(requestParameters, initOverrides);
    }

    /**
     * Delete a media file (ownership verified)
     */
    async mediaControllerRemoveV1Raw(requestParameters: MediaControllerRemoveV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling mediaControllerRemoveV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/media/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a media file (ownership verified)
     */
    async mediaControllerRemoveV1(requestParameters: MediaControllerRemoveV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.mediaControllerRemoveV1Raw(requestParameters, initOverrides);
    }

    /**
     * Upload a media file
     */
    async mediaControllerUploadV1Raw(requestParameters: MediaControllerUploadV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling mediaControllerUploadV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['metadata'] != null) {

            formParams.append('metadata', new Blob([JSON.stringify(requestParameters['metadata'])], { type: "application/json", }));
        }


        let urlPath = `/v1/media`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Upload a media file
     */
    async mediaControllerUploadV1(requestParameters: MediaControllerUploadV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.mediaControllerUploadV1Raw(requestParameters, initOverrides);
    }

}
