/* tslint:disable */
/* eslint-disable */
/**
 * Project/App Name APIs — v1
 * API v1 documentation for the backend services of Project/App Name
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RegisterDeviceTokenDto,
  SendNotificationDto,
} from '../models/index';

export interface NotificationsControllerListNotificationsV1Request {
    page?: number;
    pageSize?: number;
}

export interface NotificationsControllerMarkAsReadV1Request {
    id: string;
}

export interface NotificationsControllerRegisterDeviceV1Request {
    registerDeviceTokenDto: RegisterDeviceTokenDto;
}

export interface NotificationsControllerSendNotificationV1Request {
    userId: string;
    sendNotificationDto: SendNotificationDto;
}

/**
 * NotificationsApi - interface
 * 
 * @export
 * @interface NotificationsApiInterface
 */
export interface NotificationsApiInterface {
    /**
     * 
     * @summary Get unread notification count for current user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApiInterface
     */
    notificationsControllerGetUnreadCountV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Get unread notification count for current user
     */
    notificationsControllerGetUnreadCountV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary List current user notifications with pagination
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApiInterface
     */
    notificationsControllerListNotificationsV1Raw(requestParameters: NotificationsControllerListNotificationsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * List current user notifications with pagination
     */
    notificationsControllerListNotificationsV1(requestParameters: NotificationsControllerListNotificationsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Mark all notifications as read for current user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApiInterface
     */
    notificationsControllerMarkAllAsReadV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Mark all notifications as read for current user
     */
    notificationsControllerMarkAllAsReadV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Mark a notification as read
     * @param {string} id Notification UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApiInterface
     */
    notificationsControllerMarkAsReadV1Raw(requestParameters: NotificationsControllerMarkAsReadV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Mark a notification as read
     */
    notificationsControllerMarkAsReadV1(requestParameters: NotificationsControllerMarkAsReadV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Register a device token for push notifications
     * @param {RegisterDeviceTokenDto} registerDeviceTokenDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApiInterface
     */
    notificationsControllerRegisterDeviceV1Raw(requestParameters: NotificationsControllerRegisterDeviceV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Register a device token for push notifications
     */
    notificationsControllerRegisterDeviceV1(requestParameters: NotificationsControllerRegisterDeviceV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Send a notification to a user (admin only)
     * @param {string} userId Target user UUID
     * @param {SendNotificationDto} sendNotificationDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApiInterface
     */
    notificationsControllerSendNotificationV1Raw(requestParameters: NotificationsControllerSendNotificationV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Send a notification to a user (admin only)
     */
    notificationsControllerSendNotificationV1(requestParameters: NotificationsControllerSendNotificationV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class NotificationsApi extends runtime.BaseAPI implements NotificationsApiInterface {

    /**
     * Get unread notification count for current user
     */
    async notificationsControllerGetUnreadCountV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/notifications/unread-count`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get unread notification count for current user
     */
    async notificationsControllerGetUnreadCountV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.notificationsControllerGetUnreadCountV1Raw(initOverrides);
    }

    /**
     * List current user notifications with pagination
     */
    async notificationsControllerListNotificationsV1Raw(requestParameters: NotificationsControllerListNotificationsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/notifications`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * List current user notifications with pagination
     */
    async notificationsControllerListNotificationsV1(requestParameters: NotificationsControllerListNotificationsV1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.notificationsControllerListNotificationsV1Raw(requestParameters, initOverrides);
    }

    /**
     * Mark all notifications as read for current user
     */
    async notificationsControllerMarkAllAsReadV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/notifications/read-all`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Mark all notifications as read for current user
     */
    async notificationsControllerMarkAllAsReadV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.notificationsControllerMarkAllAsReadV1Raw(initOverrides);
    }

    /**
     * Mark a notification as read
     */
    async notificationsControllerMarkAsReadV1Raw(requestParameters: NotificationsControllerMarkAsReadV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling notificationsControllerMarkAsReadV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/notifications/{id}/read`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Mark a notification as read
     */
    async notificationsControllerMarkAsReadV1(requestParameters: NotificationsControllerMarkAsReadV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.notificationsControllerMarkAsReadV1Raw(requestParameters, initOverrides);
    }

    /**
     * Register a device token for push notifications
     */
    async notificationsControllerRegisterDeviceV1Raw(requestParameters: NotificationsControllerRegisterDeviceV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['registerDeviceTokenDto'] == null) {
            throw new runtime.RequiredError(
                'registerDeviceTokenDto',
                'Required parameter "registerDeviceTokenDto" was null or undefined when calling notificationsControllerRegisterDeviceV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/notifications/devices`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['registerDeviceTokenDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Register a device token for push notifications
     */
    async notificationsControllerRegisterDeviceV1(requestParameters: NotificationsControllerRegisterDeviceV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.notificationsControllerRegisterDeviceV1Raw(requestParameters, initOverrides);
    }

    /**
     * Send a notification to a user (admin only)
     */
    async notificationsControllerSendNotificationV1Raw(requestParameters: NotificationsControllerSendNotificationV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling notificationsControllerSendNotificationV1().'
            );
        }

        if (requestParameters['sendNotificationDto'] == null) {
            throw new runtime.RequiredError(
                'sendNotificationDto',
                'Required parameter "sendNotificationDto" was null or undefined when calling notificationsControllerSendNotificationV1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/notifications`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['sendNotificationDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Send a notification to a user (admin only)
     */
    async notificationsControllerSendNotificationV1(requestParameters: NotificationsControllerSendNotificationV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.notificationsControllerSendNotificationV1Raw(requestParameters, initOverrides);
    }

}
