/* tslint:disable */
/* eslint-disable */
/**
 * Project/App Name APIs — v1
 * API v1 documentation for the backend services of Project/App Name
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateWebhookDto,
  UpdateWebhookDto,
} from '../models/index';

export interface WebhooksControllerCreateV1Request {
    createWebhookDto: CreateWebhookDto;
}

export interface WebhooksControllerFindOneV1Request {
    id: string;
}

export interface WebhooksControllerGetDeliveriesV1Request {
    id: string;
    page?: number;
    pageSize?: number;
}

export interface WebhooksControllerRemoveV1Request {
    id: string;
}

export interface WebhooksControllerSendTestEventV1Request {
    id: string;
}

export interface WebhooksControllerUpdateV1Request {
    id: string;
    updateWebhookDto: UpdateWebhookDto;
}

/**
 * WebhooksApi - interface
 * 
 * @export
 * @interface WebhooksApiInterface
 */
export interface WebhooksApiInterface {
    /**
     * 
     * @summary Create a new webhook subscription
     * @param {CreateWebhookDto} createWebhookDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    webhooksControllerCreateV1Raw(requestParameters: WebhooksControllerCreateV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Create a new webhook subscription
     */
    webhooksControllerCreateV1(requestParameters: WebhooksControllerCreateV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary List all webhooks for the current user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    webhooksControllerFindAllV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * List all webhooks for the current user
     */
    webhooksControllerFindAllV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get webhook details by ID
     * @param {string} id Webhook UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    webhooksControllerFindOneV1Raw(requestParameters: WebhooksControllerFindOneV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Get webhook details by ID
     */
    webhooksControllerFindOneV1(requestParameters: WebhooksControllerFindOneV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary List delivery attempts for a webhook
     * @param {string} id Webhook UUID
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    webhooksControllerGetDeliveriesV1Raw(requestParameters: WebhooksControllerGetDeliveriesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * List delivery attempts for a webhook
     */
    webhooksControllerGetDeliveriesV1(requestParameters: WebhooksControllerGetDeliveriesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Delete a webhook
     * @param {string} id Webhook UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    webhooksControllerRemoveV1Raw(requestParameters: WebhooksControllerRemoveV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete a webhook
     */
    webhooksControllerRemoveV1(requestParameters: WebhooksControllerRemoveV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Send a test event to verify the webhook endpoint
     * @param {string} id Webhook UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    webhooksControllerSendTestEventV1Raw(requestParameters: WebhooksControllerSendTestEventV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Send a test event to verify the webhook endpoint
     */
    webhooksControllerSendTestEventV1(requestParameters: WebhooksControllerSendTestEventV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Update a webhook
     * @param {string} id Webhook UUID
     * @param {UpdateWebhookDto} updateWebhookDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    webhooksControllerUpdateV1Raw(requestParameters: WebhooksControllerUpdateV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Update a webhook
     */
    webhooksControllerUpdateV1(requestParameters: WebhooksControllerUpdateV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI implements WebhooksApiInterface {

    /**
     * Create a new webhook subscription
     */
    async webhooksControllerCreateV1Raw(requestParameters: WebhooksControllerCreateV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createWebhookDto'] == null) {
            throw new runtime.RequiredError(
                'createWebhookDto',
                'Required parameter "createWebhookDto" was null or undefined when calling webhooksControllerCreateV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webhooks`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createWebhookDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new webhook subscription
     */
    async webhooksControllerCreateV1(requestParameters: WebhooksControllerCreateV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.webhooksControllerCreateV1Raw(requestParameters, initOverrides);
    }

    /**
     * List all webhooks for the current user
     */
    async webhooksControllerFindAllV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webhooks`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * List all webhooks for the current user
     */
    async webhooksControllerFindAllV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.webhooksControllerFindAllV1Raw(initOverrides);
    }

    /**
     * Get webhook details by ID
     */
    async webhooksControllerFindOneV1Raw(requestParameters: WebhooksControllerFindOneV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling webhooksControllerFindOneV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webhooks/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get webhook details by ID
     */
    async webhooksControllerFindOneV1(requestParameters: WebhooksControllerFindOneV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.webhooksControllerFindOneV1Raw(requestParameters, initOverrides);
    }

    /**
     * List delivery attempts for a webhook
     */
    async webhooksControllerGetDeliveriesV1Raw(requestParameters: WebhooksControllerGetDeliveriesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling webhooksControllerGetDeliveriesV1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webhooks/{id}/deliveries`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * List delivery attempts for a webhook
     */
    async webhooksControllerGetDeliveriesV1(requestParameters: WebhooksControllerGetDeliveriesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.webhooksControllerGetDeliveriesV1Raw(requestParameters, initOverrides);
    }

    /**
     * Delete a webhook
     */
    async webhooksControllerRemoveV1Raw(requestParameters: WebhooksControllerRemoveV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling webhooksControllerRemoveV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webhooks/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a webhook
     */
    async webhooksControllerRemoveV1(requestParameters: WebhooksControllerRemoveV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.webhooksControllerRemoveV1Raw(requestParameters, initOverrides);
    }

    /**
     * Send a test event to verify the webhook endpoint
     */
    async webhooksControllerSendTestEventV1Raw(requestParameters: WebhooksControllerSendTestEventV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling webhooksControllerSendTestEventV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webhooks/{id}/test`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Send a test event to verify the webhook endpoint
     */
    async webhooksControllerSendTestEventV1(requestParameters: WebhooksControllerSendTestEventV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.webhooksControllerSendTestEventV1Raw(requestParameters, initOverrides);
    }

    /**
     * Update a webhook
     */
    async webhooksControllerUpdateV1Raw(requestParameters: WebhooksControllerUpdateV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling webhooksControllerUpdateV1().'
            );
        }

        if (requestParameters['updateWebhookDto'] == null) {
            throw new runtime.RequiredError(
                'updateWebhookDto',
                'Required parameter "updateWebhookDto" was null or undefined when calling webhooksControllerUpdateV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webhooks/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['updateWebhookDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update a webhook
     */
    async webhooksControllerUpdateV1(requestParameters: WebhooksControllerUpdateV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.webhooksControllerUpdateV1Raw(requestParameters, initOverrides);
    }

}
